### ISSUE TITLE
Restroom Detail View: Scroll visibility on comments/directions

### ISSUE THREAD

**Issue by tkwidmer** [RefugeRestrooms/refuge-ios#109]
Ive been getting a couple of complaints via the contact form about the Detail View and the Scroll functionality. Many users are having a hard time seeing the scroll functionality on those boxes. Here is an example of some user feedback

> hey I noticed on the app that sometimes when the info section has a good amount of text, then the 
> comments are cut off on the bottom and there's no way to scroll down to view them
> meh?
> just wanted to mention
> thanks

One option here would be to shoot for the mock a little closer, not worrying about the entire page scrolling. The original mock (although here is shown for mobile web) had the info at the top, and then would have listed the directions and comments -- however much content there was at the bottom. I dont have a huge burden, but wanted to bring it to your attention that there has been some confusion with current functionality. 

![detail view mock](https://github.com/RefugeRestrooms/refuge_assets/blob/master/specs/original_specs/showpage.jpg?raw=true)

**Comment by hkellaway** [comment]
@tkwidmer yes, i could see it getting cutoff with smaller devices. this quickest fix is to make the current design not take up as much vertical space. i will make that update for v1.1.1 and make an issue for creating a better (i.e. scrollable or dynamic or different altogether, as with the mock) layout for a future update

**Comment by hkellaway** [comment]
@tkwidmer see build 1.1.1 (2)
