### ISSUE TITLE
Restroom Details: Some apostrophe's are preceded by an \

### ISSUE THREAD

**Issue by hkellaway** [RefugeRestrooms/refuge-ios#114]
See: https://github.com/RefugeRestrooms/refugerestrooms/issues/229

**Comment by TazeTSchnitzel** [comment]
> apostrophe's
>'s

argh, I hate you :p

**Comment by hkellaway** [comment]
A fix for this will go out in the next update - thanks @TazeTSchnitzel !

**Comment by TazeTSchnitzel** [comment]
Is that the same one that fixed the scrolling issue? Because I've gotten that update and it didn't fix this issue

**Comment by hkellaway** [comment]
@TazeTSchnitzel good question - the bug you reported is fixed in the next update, currently pending Apple review
